In [1]:
import torch

# Creating Tensors

In [2]:
a=torch.empty(2,3) #created tensor with no values(empty)
b=torch.zeros(2,5) #tensor with all zeroes
c=torch.ones(2,4) #tensor with all ones
d=torch.rand(2,5) #we will get random values every time we run this

In [3]:
print(a,b,c,d)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) tensor([[0.0321, 0.8806, 0.4332, 0.0656, 0.7369],
        [0.7846, 0.9249, 0.7879, 0.6583, 0.5490]])


In [4]:
b.shape

torch.Size([2, 5])

In [5]:
torch.manual_seed(100)
torch.rand(2,5) #using seed to gain reproducability

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180]])

In [6]:
torch.manual_seed(100)
torch.rand(2,5) #same tensor values as of previous one with using seed

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180]])

In [7]:
#we can also create custom tensor by using tensor
torch.tensor([[1,3,6],[6,1.2,4.5]])

tensor([[1.0000, 3.0000, 6.0000],
        [6.0000, 1.2000, 4.5000]])

In [8]:
print(torch.arange(0,10,2))
print(torch.linspace(0,10,15))
print(torch.ones_like(torch.arange(0,10,2))) #ones matrix with the size of 5 as it has arange method with 0,10,2 which means 5 values
print(torch.eye(6)) #identity matrix of 6 cross 6
print(torch.full((2,3),5)) #matrix of 2 cross 3 and it should have 5 all around

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571,  3.5714,  4.2857,  5.0000,
         5.7143,  6.4286,  7.1429,  7.8571,  8.5714,  9.2857, 10.0000])
tensor([1, 1, 1, 1, 1])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5]])


In [9]:
print(torch.empty_like(c)) #empty matrix with the shape of c(matrix created above)

tensor([[6.5023e+01, 0.0000e+00, 6.5176e+01, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 1.1210e-43, 0.0000e+00]])


# Data Types of Tensors

In [10]:
a.dtype

torch.float32

#Assigning datatype of tensors

In [11]:
x=torch.tensor([[1,5,10],[2.0,6.0,5.0]], dtype=torch.int32)
y=torch.tensor([[1.2,2.4,5],[2.1,4,6]], dtype=torch.float64)

In [12]:
print(x,y)

tensor([[ 1,  5, 10],
        [ 2,  6,  5]], dtype=torch.int32) tensor([[1.2000, 2.4000, 5.0000],
        [2.1000, 4.0000, 6.0000]], dtype=torch.float64)


# Changing datatype of tensor

In [13]:
x.to(torch.float64)

tensor([[ 1.,  5., 10.],
        [ 2.,  6.,  5.]], dtype=torch.float64)

# Mathematical opr

In [14]:
#Scaler
tens1=torch.tensor([[1,2,3],[4,5,6]])
tens1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
#these operations will create a new tensor to store result(this is not inplace method)
#add
add=tens1+5

#sub
sub=tens1-2

#mul
mul=tens1*2

#div
div=tens1/2

#exp
exp=tens1**2

#mod
mod=tens1%2
#floor div
floor_div=tens1//2
print(add,sub,mul,div,exp,mod,floor_div)

tensor([[ 6,  7,  8],
        [ 9, 10, 11]]) tensor([[-1,  0,  1],
        [ 2,  3,  4]]) tensor([[ 2,  4,  6],
        [ 8, 10, 12]]) tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]]) tensor([[ 1,  4,  9],
        [16, 25, 36]]) tensor([[1, 0, 1],
        [0, 1, 0]]) tensor([[0, 1, 1],
        [2, 2, 3]])


In [16]:
#Element wise opr
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[4,8,2],[7,8,2.2]])
print("add=",a+b,"sub=",a-b,"mul=",a*b,"div=", a/b, "power=", a**b,"mod=" ,a%b,"Floor=" ,a//b)

add= tensor([[ 5.0000, 10.0000,  5.0000],
        [11.0000, 13.0000,  8.2000]]) sub= tensor([[-3.0000, -6.0000,  1.0000],
        [-3.0000, -3.0000,  3.8000]]) mul= tensor([[ 4.0000, 16.0000,  6.0000],
        [28.0000, 40.0000, 13.2000]]) div= tensor([[0.2500, 0.2500, 1.5000],
        [0.5714, 0.6250, 2.7273]]) power= tensor([[1.0000e+00, 2.5600e+02, 9.0000e+00],
        [1.6384e+04, 3.9062e+05, 5.1515e+01]]) mod= tensor([[1.0000, 2.0000, 1.0000],
        [4.0000, 5.0000, 1.6000]]) Floor= tensor([[0., 0., 1.],
        [0., 0., 2.]])


In [17]:
c=torch.tensor([[1.2,-2.5,-1.1],[-3.2,-6.4,9.9]])
print(torch.abs(c), torch.neg(c),torch.max(c), torch.min(c))


tensor([[1.2000, 2.5000, 1.1000],
        [3.2000, 6.4000, 9.9000]]) tensor([[-1.2000,  2.5000,  1.1000],
        [ 3.2000,  6.4000, -9.9000]]) tensor(9.9000) tensor(-6.4000)


In [18]:
d=torch.tensor([[1.4,5.6,2.2],[5.8,5.9,1.1]])
d.ceil(), d.floor(), d.trunc(), d.frac(), d.round(), d.sqrt(), d.rsqrt(), d.reciprocal(),d.clamp(2,4)#2 is min and 4 is max..clamping will be done between these

(tensor([[2., 6., 3.],
         [6., 6., 2.]]),
 tensor([[1., 5., 2.],
         [5., 5., 1.]]),
 tensor([[1., 5., 2.],
         [5., 5., 1.]]),
 tensor([[0.4000, 0.6000, 0.2000],
         [0.8000, 0.9000, 0.1000]]),
 tensor([[1., 6., 2.],
         [6., 6., 1.]]),
 tensor([[1.1832, 2.3664, 1.4832],
         [2.4083, 2.4290, 1.0488]]),
 tensor([[0.8452, 0.4226, 0.6742],
         [0.4152, 0.4117, 0.9535]]),
 tensor([[0.7143, 0.1786, 0.4545],
         [0.1724, 0.1695, 0.9091]]),
 tensor([[2.0000, 4.0000, 2.2000],
         [4.0000, 4.0000, 2.0000]]))

# Reduction operations

In [19]:
d=torch.tensor([[1.4,5.6,2.2],[5.8,5.9,1.1]])
print(d)
print("    ")
print(d.sum())#total sum of all elements in tensor
print(d.sum(dim=0))#sum along columns
print(d.sum(dim=1))#sum along rows

tensor([[1.4000, 5.6000, 2.2000],
        [5.8000, 5.9000, 1.1000]])
    
tensor(22.)
tensor([ 7.2000, 11.5000,  3.3000])
tensor([ 9.2000, 12.8000])


In [20]:
print(d.mean()) #it only works if dtype of tensor is float
print(d.mean(dim=0),d.mean(dim=1))
print(d.median())

tensor(3.6667)
tensor([3.6000, 5.7500, 1.6500]) tensor([3.0667, 4.2667])
tensor(2.2000)


In [21]:
print(d.prod(),d.std(), d.var(), d.argmax(), d.argmin()) #argmax gives the index of max no. of tensor and argmin is vice versa

tensor(649.2492) tensor(2.3304) tensor(5.4307) tensor(4) tensor(5)


# Matrix operations

In [22]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f,g)

tensor([[4, 3, 8],
        [8, 4, 4]]) tensor([[1, 0],
        [4, 3],
        [8, 7]])


In [23]:
f.matmul(g) #multiplication of two matrices

tensor([[80, 65],
        [56, 40]])

In [24]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])
#dot product
vector1.dot(vector2)

tensor(32)

In [25]:
#transpose
e=torch.tensor([[1,6],[2,4]])
print(e)
e.transpose(0,1)

tensor([[1, 6],
        [2, 4]])


tensor([[1, 2],
        [6, 4]])

In [26]:
#Determinant
g=torch.randint(size=(2,2),low=0,high=10,dtype=torch.float32)
g.det(), g.inverse()

(tensor(4.),
 tensor([[ 0.2500, -1.5000],
         [ 0.0000,  1.0000]]))

# Comparison Operations

In [27]:
f=torch.tensor([[1,2,3],[5,8,10]])
g=torch.tensor([[9,0,2],[5,6,10]])
print(f>g, f>=g, f<g, f<=g, f==g, f!=g) #gives boolean value

tensor([[False,  True,  True],
        [False,  True, False]]) tensor([[False,  True,  True],
        [ True,  True,  True]]) tensor([[ True, False, False],
        [False, False, False]]) tensor([[ True, False, False],
        [ True, False,  True]]) tensor([[False, False, False],
        [ True, False,  True]]) tensor([[ True,  True,  True],
        [False,  True, False]])


# Inplace operations

In [28]:
add1=torch.tensor([[2,3],[6,7]])
add2=torch.tensor([[5,4],[-1,-8]])
print(add1,add2)

tensor([[2, 3],
        [6, 7]]) tensor([[ 5,  4],
        [-1, -8]])


In [29]:
add1.add_(add2) #this will add add2 tensor to add1 tensor and store resulted or new modified tensor to add1 itself without creating new tensor which will occupy nd waste space

tensor([[ 7,  7],
        [ 5, -1]])

In [30]:
add1 #this original add1 is modified so it's an implace method(permanent modification)

tensor([[ 7,  7],
        [ 5, -1]])

In [31]:
add2.relu_() #relu converts all negatives to 0

tensor([[5, 4],
        [0, 0]])

# How to copy a tensor

-when we copy a tensor with classical method..the both variables refrences to same memory location instead of creating a new memory..because of this, when we change val of first variable, this also changes the second(copied variable) so to overcome this, we use clone method of pytorch..

In [32]:
#problem
x=torch.tensor([[2,5],[7,8]])
y=x
y

tensor([[2, 5],
        [7, 8]])

In [33]:
x

tensor([[2, 5],
        [7, 8]])

In [34]:
y

tensor([[2, 5],
        [7, 8]])

In [35]:
x.add_(2)
print(x,y) #changing x changed y

tensor([[ 4,  7],
        [ 9, 10]]) tensor([[ 4,  7],
        [ 9, 10]])


In [36]:
#Solution
cloned=x.clone()

In [37]:
cloned #new copied tensor formed on new memory location

tensor([[ 4,  7],
        [ 9, 10]])

In [38]:
x.add_(2) #modifying x tensor

tensor([[ 6,  9],
        [11, 12]])

In [39]:
cloned #no change in cloned tensor even after changing a tensor

tensor([[ 4,  7],
        [ 9, 10]])

# tensor operations

In [40]:
torch.cuda.is_available()

True

In [41]:
device=torch.device('cuda')
torch.rand((2,4),device=device)#new tensor on gpu

tensor([[0.3563, 0.0303, 0.7088, 0.2009],
        [0.0224, 0.9896, 0.3737, 0.0823]], device='cuda:0')

In [42]:
#if we want to move a cpu tensor to gpu
a.to(device)

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

# Reshaping tensors

In [43]:
z=torch.zeros(2,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
z.reshape(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [45]:
z.flatten()

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
k=torch.rand(2,2,3)
permuted=k.permute(2,0,1)
print(k,permuted,permuted.shape)

tensor([[[0.7445, 0.4892, 0.2426],
         [0.7003, 0.5277, 0.2472]],

        [[0.7909, 0.4235, 0.0169],
         [0.2209, 0.9535, 0.7064]]]) tensor([[[0.7445, 0.7003],
         [0.7909, 0.2209]],

        [[0.4892, 0.5277],
         [0.4235, 0.9535]],

        [[0.2426, 0.2472],
         [0.0169, 0.7064]]]) torch.Size([3, 2, 2])


In [47]:
u=torch.rand([226,226,3])
u

tensor([[[0.1629, 0.8902, 0.5163],
         [0.0359, 0.6476, 0.3430],
         [0.3182, 0.5261, 0.0447],
         ...,
         [0.0051, 0.4490, 0.5105],
         [0.3744, 0.1224, 0.2298],
         [0.2792, 0.0859, 0.9755]],

        [[0.9524, 0.8462, 0.1944],
         [0.0960, 0.4429, 0.2946],
         [0.1774, 0.9362, 0.8609],
         ...,
         [0.1313, 0.3873, 0.2407],
         [0.2520, 0.8043, 0.2033],
         [0.3674, 0.1363, 0.4875]],

        [[0.9275, 0.2509, 0.7050],
         [0.4019, 0.8103, 0.9580],
         [0.6881, 0.3997, 0.7121],
         ...,
         [0.8861, 0.9689, 0.9349],
         [0.3671, 0.1410, 0.4402],
         [0.1493, 0.6974, 0.4177]],

        ...,

        [[0.8528, 0.2039, 0.9859],
         [0.5002, 0.2753, 0.8176],
         [0.7056, 0.6916, 0.2272],
         ...,
         [0.3676, 0.2753, 0.1134],
         [0.2404, 0.4860, 0.4614],
         [0.6268, 0.0938, 0.6519]],

        [[0.3427, 0.4476, 0.2728],
         [0.6183, 0.3829, 0.2192],
         [0.

In [48]:
u.unsqueeze(0).shape #this added a dimension on index 0

torch.Size([1, 226, 226, 3])

In [49]:
s=torch.rand(1,3)
s.squeeze(0).shape

torch.Size([3])

# numpy to pytorch and vice versa

In [50]:
pyt=torch.tensor([1,2,3])

In [51]:
numpyarr=pyt.numpy()

In [52]:
print(type(pyt), type(numpyarr))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [53]:
pytfromnumpy=torch.from_numpy(numpyarr)
print(type(numpyarr),type(pytfromnumpy))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
